# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ad2c37ace6b2a281b37125751368f2e5cfb06d493686807e797a8057b1440ea3ab4042946354be4101ba69156e24b6712200021ac6fadb3be950bce2fb8929c

test:
  secret_key_base: 9435119aeed5386a947c6043dbe5cf77199b38e7579542c694d6f0972e215996c54e85ba82bf6e1518deb75a24dbb96d516be9a9ba80b0106446493f68b0a44a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
